---
# Setup LAMP Stack
- hosts: webservers
  become: yes
  gather_facts: no



  

  pre_tasks:
    - raw: sudo apt-get -y install python
 
 
  # action: setup will gather facts after python has been installed
    - action: setup

  roles:
   - prep
  - apache2
  - mysql
  - php
  - vsftpd
