---
# tasks file for php
# - name: Install php-fpm & php extensions

    - name: install php
      apt:
        pkg:
          - php
          - php-mysql
          - php-bcmath
          - php-bz2
          - php-common
          - php-curl
          - php-mbstring
          - php-mysql
          - php-readline
          - php-xml
          - php-xsl
          - php-zip
        state: present
